<div class="sidebar">
      <a href="index.php"><h1>WebCel</h1></a>
      <h2>Productos</h2>
      <ul>
        <li><a href="productoAdd.php">Agregar un producto</a></li>
        <li><a href="productoDel.php">Eliminar un producto</a></li>
        <li><a href="productoMod.php">Modificar un producto</a></li>
      </ul>
      
      <h2>Categor&iacute;as</h2>
      <ul>
        <li><a href="categoriasAdd.php">Agregar categor&iacute;a</a></li>
        <li><a href="categoriasMod.php">Modificar categor&iacute;a</a></li>
      </ul>
      
      <h2>Consultas</h2>
      <ul>
        <li><a href="listaCategorias.php">Lista de categor&iacute;as</a></li>
        <li><a href="consultas.php?CAT=-1&PAI=-1">Consultas de productos</a></li>
      </ul>
    </div>